apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "hk-cobe-signal"
  namespace: "cobe-signal"
  labels:
    app: "hk-cobe-signal"
spec:
  serviceName: "hk-cobe-signal"
  replicas: 3
  selector:
    matchLabels:
      app: "hk-cobe-signal"
  template:
    metadata:
      labels:
        app: "hk-cobe-signal"
    spec:
      terminationGracePeriodSeconds: 20
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - hk-cobe-signal
              topologyKey: kubernetes.io/hostname
      containers:
      - name: "cobe-signal-sha256-1"
        image: "gcr.io/sunlife001/cobe-signal@sha256:dd24b104a4d8aa1a202df0b716dc2fd08da6b15a52bac6b2c4dfd5a90b043669"
 volumeClaimTemplates:
 - metadata:
     name: signal-data
     annotations:
       volume.beta.kubernetes.io/storage-class: "standard"
   spec:
     accessModes: [ "ReadWriteOnce" ]
     resources:
       requests:
         storage: 100Gi
